settings:
  classes: ['motorcycle', 'car', 'bus', 'truck']
  size: [1280,720]
  checkpoint: "./models/deepsort/deep/checkpoint/ckpt.t7"
  cam:
    cam_04:
      video: './datasets/videos/cam_04.mp4'
      boxes: './results/detection/cam_04'
      zone: './datasets/annotations/cam_04.json'
      tracking_config:
        MAX_DIST: 0.3
        MIN_CONFIDENCE: 0.5
        NMS_MAX_OVERLAP: 0.9
        MAX_IOU_DISTANCE: 0.8
        MAX_AGE: 40
        N_INIT: 4
        NN_BUDGET: 60
    cam_05:
      video: './datasets/videos/cam_05.mp4'
      boxes: './results/detection/cam_05'
      zone: './datasets/annotations/cam_04.json'
      tracking_config:
        MAX_DIST: 0.3
        MIN_CONFIDENCE: 0.5
        NMS_MAX_OVERLAP: 0.9
        MAX_IOU_DISTANCE: 0.8
        MAX_AGE: 40
        N_INIT: 4
        NN_BUDGET: 60

    
